// SVG <pattern> defs for the map's ground texture — a real photo (owner-supplied,
// generated by them via AI, explicit permission given 2026-08-15 to use it without a
// licensing concern), not a procedural drawing. Two earlier procedural attempts (blade
// strokes, then mottled blobs) both read as "boring"/mechanical to the owner; a real
// photo is the actual fix. Built once when the SVG is parsed (ColonyMap.tsx's
// parseColonySvg), same precedent as plotDimensionOverlay.ts's buildDimensionArrowMarker.
const SVG_NS = "http://www.w3.org/2000/svg";

function el<K extends keyof SVGElementTagNameMap>(
  tag: K,
  attrs: Record<string, string>,
): SVGElementTagNameMap[K] {
  const node = document.createElementNS(SVG_NS, tag);
  for (const [key, value] of Object.entries(attrs)) node.setAttribute(key, value);
  return node;
}

// The owner wasn't sure their source photo tiles seamlessly, so this mirrors it into
// a 2x2 block (normal / flip-x / flip-y / flip-both) instead of repeating it plain —
// a mirrored copy of an edge always matches itself exactly, so the tile has no seam
// regardless of whether the source photo does. The visible cost is a symmetric
// "kaleidoscope" repeat instead of a fully random one; at ground-texture scale that
// reads as fine, and it's the standard way to make an arbitrary photo tile safely.

// Small overlap on every quadrant image, grown symmetrically around its own quadrant
// centre rather than resized in place — found live: with each <image> sized to its
// exact quadrant, the browser's own edge antialiasing left a faint but visible grid
// line at every join (owner: "it is making a pattern i dont want"), even though the
// mirrored content matches exactly either side of it. A hair of overlap hides the
// antialiasing seam in content instead of a gap.
const SEAM_OVERLAP = 1;

function buildMirroredPhotoPattern(id: string, href: string, tileW: number, tileH: number): SVGPatternElement {
  const pattern = el("pattern", {
    id,
    width: String(tileW * 2),
    height: String(tileH * 2),
    patternUnits: "userSpaceOnUse",
  });
  const quadrants: { transform: string }[] = [
    { transform: "" }, // top-left, unflipped
    { transform: `translate(${tileW * 2} 0) scale(-1 1)` }, // top-right
    { transform: `translate(0 ${tileH * 2}) scale(1 -1)` }, // bottom-left
    { transform: `translate(${tileW * 2} ${tileH * 2}) scale(-1 -1)` }, // bottom-right
  ];
  for (const { transform } of quadrants) {
    const image = el("image", {
      href,
      x: String(-SEAM_OVERLAP),
      y: String(-SEAM_OVERLAP),
      width: String(tileW + SEAM_OVERLAP * 2),
      height: String(tileH + SEAM_OVERLAP * 2),
      preserveAspectRatio: "xMidYMid slice",
    });
    // xlink:href alongside plain href — older WebKit (tier-3.md's target device) only
    // recognises the namespaced form for SVG <image>.
    image.setAttributeNS("http://www.w3.org/1999/xlink", "xlink:href", href);
    if (transform) image.setAttribute("transform", transform);
    pattern.appendChild(image);
  }
  return pattern;
}

// Owner's photo is 220x198. Tile size was 90x81 originally — at the 1000-wide site that
// repeated the mirrored 2x2 block ~5.5 times across, and the photo's own AI-generated
// swirl/weave structure is strong enough that the repeat read as an obvious kaleidoscope
// rather than plain texture (owner: "it is making a pattern i dont want that"). Sized up
// so the block repeats ~3 times across the site instead — fewer, larger repeats are far
// less noticeable than many small ones, even though each repeat is individually softer
// (see grass-satellite.jpg's own blur pass, applied for the same reason).
const GRASS_TILE_W = 160;
const GRASS_TILE_H = 144; // matches the source photo's 220:198 aspect ratio

// Used by the site's own SVG for .garden only — the ground itself comes from the
// separate world-ground layer (buildWorldGroundSvg below), not from anything in this
// document. Deliberately its own function with its own id ("texture-garden" only, no
// "texture-grass") rather than sharing buildWorldGroundSvg's defs: SVG ids aren't
// scoped per <svg> sub-root, they're unique per *document*, and this app puts the
// site's SVG and the world-ground SVG in the same live DOM as two sibling overlay
// layers — a shared id between them resolves ambiguously and silently renders the
// wrong pattern (found live: the world ground rect picked up the wrong tile geometry
// once both documents defined a "texture-grass" pattern).
export function buildGardenPatternDefs(grassPhotoUrl: string): SVGDefsElement {
  const defs = el("defs", {});
  const gardenPattern = buildMirroredPhotoPattern("texture-garden", grassPhotoUrl, GRASS_TILE_W, GRASS_TILE_H);
  gardenPattern.appendChild(
    el("rect", {
      width: String(GRASS_TILE_W * 2),
      height: String(GRASS_TILE_H * 2),
      class: "texture-garden-tint",
    }),
  );
  defs.appendChild(gardenPattern);
  return defs;
}

// One rect covering the whole viewport, painted first (ColonyMap.tsx inserts it as
// the SVG's first child) so every plot/road/garden shape paints over it — this is
// what makes the ground texture one continuous field instead of a separate tile per
// plot (patternUnits="userSpaceOnUse" ties every pattern's tile grid to this same
// shared (0, 0) origin, so nothing seams at plot boundaries). width/height are
// percentages of the SVG viewport, not the viewBox, so this covers any colony's
// fixture without needing its exact dimensions passed in.
export function buildGroundRect(): SVGRectElement {
  return el("rect", { x: "0", y: "0", width: "100%", height: "100%", class: "texture-ground-fill" });
}

// Padding around the site, in multiples of the site's own width/height, for the
// world-ground layer below — big enough that panning or zooming out still shows ground
// texture instead of running out into empty space, without making the SVG unnecessarily
// large. Moved here (not ColonyMap.tsx) so the constant lives next to the one function
// that uses it.
const WORLD_PAD_FACTOR = 1.5;

export interface WorldLayerBounds {
  worldWidth: number;
  worldHeight: number;
  worldBounds: [[number, number], [number, number]];
}

// ColonyMap.tsx passes viewBoxWidth/Height straight off the parsed site SVG, then feeds
// worldWidth/worldHeight into buildWorldGroundSvg and worldBounds into L.svgOverlay.
export function computeWorldLayerBounds(viewBoxWidth: number, viewBoxHeight: number): WorldLayerBounds {
  const worldPadX = viewBoxWidth * WORLD_PAD_FACTOR;
  const worldPadY = viewBoxHeight * WORLD_PAD_FACTOR;
  return {
    worldWidth: viewBoxWidth + 2 * worldPadX,
    worldHeight: viewBoxHeight + 2 * worldPadY,
    worldBounds: [
      [-worldPadY, -worldPadX],
      [viewBoxHeight + worldPadY, viewBoxWidth + worldPadX],
    ],
  };
}

// A second, standalone SVG document (own <defs>, own ground rect) added to the map as
// a separate Leaflet overlay layer beneath the site's own SVG, sized to a much larger
// "world" than the site itself (ColonyMap.tsx computes worldBounds). Because it's a
// real Leaflet layer sharing the map's own coordinate transform — not a CSS
// background image on the container — it pans and zooms in exact lockstep with the
// site (owner correction: "make it feel like everything is getting zoomed in, not
// just the rectangle"). Deliberately a separate SVG element rather than padding the
// site SVG's own viewBox: useSelectedPlotOverlay.ts reads the site SVG's viewBox
// height directly to compute pan-to-selection targets, and this codebase has already
// been bitten once by a viewBox/bounds mismatch breaking that exact math (see
// ColonyMap.tsx's ZOOM_DETAIL_MARGIN comment) — this approach can't touch it at all.
export function buildWorldGroundSvg(grassPhotoUrl: string, worldWidth: number, worldHeight: number): SVGSVGElement {
  const svg = el("svg", {
    viewBox: `0 0 ${worldWidth} ${worldHeight}`,
  });
  const defs = el("defs", {});
  defs.appendChild(buildMirroredPhotoPattern("texture-grass", grassPhotoUrl, GRASS_TILE_W, GRASS_TILE_H));
  svg.appendChild(defs);
  svg.appendChild(buildGroundRect());
  return svg;
}

// Road grain — a handful of fixed, hand-placed flecks over the flat asphalt fill (owner
// ask: "a little road like texture would be amazing"), not an image or an SVG filter
// (tier-3.md: filters force a repaint on every zoom step). One small tile, resolved by
// the browser's own pattern tiling rather than per-frame JS, so the cost is the same as
// any other static fill. Roads only ever exist in the site's own SVG, never the
// world-ground layer, so "texture-road" can't collide with a same-named id there.
const ROAD_TILE = 22;
const ROAD_FLECKS: { x: number; y: number; r: number; cls: string }[] = [
  { x: 4, y: 6, r: 1.3, cls: "texture-road-fleck-light" },
  { x: 14, y: 3, r: 0.9, cls: "texture-road-fleck-dark" },
  { x: 19, y: 10, r: 1.5, cls: "texture-road-fleck-light" },
  { x: 8, y: 14, r: 1, cls: "texture-road-fleck-dark" },
  { x: 2, y: 19, r: 1.2, cls: "texture-road-fleck-light" },
  { x: 16, y: 18, r: 0.9, cls: "texture-road-fleck-dark" },
];

export function buildRoadPatternDefs(): SVGDefsElement {
  const defs = el("defs", {});
  const pattern = el("pattern", {
    id: "texture-road",
    width: String(ROAD_TILE),
    height: String(ROAD_TILE),
    patternUnits: "userSpaceOnUse",
  });
  pattern.appendChild(
    el("rect", { width: String(ROAD_TILE), height: String(ROAD_TILE), class: "texture-road-base" }),
  );
  for (const { x, y, r, cls } of ROAD_FLECKS) {
    pattern.appendChild(el("circle", { cx: String(x), cy: String(y), r: String(r), class: cls }));
  }
  defs.appendChild(pattern);
  return defs;
}
